{
 "title": "Minecraft Server",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "JVM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mc_jvm_memory{job=\"minecraft-stats\", type=\"max\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "mc_jvm_memory{job=\"minecraft-stats\", type=\"allocated\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mc_jvm_memory{job=\"minecraft-stats\", type=\"free\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "mc_players_online_total{world=\"world\"}",
     "legendFormat": "Overworld"
    },
    {
     "expr": "mc_players_online_total{world=\"world_nether\"}",
     "legendFormat": "Nether"
    },
    {
     "expr": "mc_players_online_total{world=\"world_the_end\"}",
     "legendFormat": "The End"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "mc_jvm_threads_current", "legendFormat": "Current" }
   ]
  },
  {
   "title": "Online Players",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mc_players_online_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tick Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mc_tps", "legendFormat": "Tick Rate" }
   ]
  }
 ]
}