{
 "title": "いづなハウス",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "お外",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_currentconditions{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Rain"
    }
   ]
  },
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_sunrise{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Rain"
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_sunset{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Rain"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_temperature{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "openweather_feels_like{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Apparent Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_humidity{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "SeaLevel Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_pressure{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "openweather_temperature{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "openweather_feels_like{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Apparent Temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "openweather_humidity{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Humidity"
    }
   ]
  },
  {
   "title": "SeaLevel Pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "openweather_pressure{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "SeaLevel Pressure"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_wind_speed{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Wind Speed"
    },
    {
     "expr": "openweather_wind_gust{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Wind Gust"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openweather_rain1h{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Rain 1Hour"
    },
    {
     "expr": "openweather_snow1h{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Snow 1Hour"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "expr": "openweather_wind_speed{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Wind Speed"
    },
    {
     "expr": "openweather_wind_gust{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Wind Speed"
    }
   ]
  },
  {
   "title": "Rainfall / Snowfall",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "openweather_rain1h{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Rainfall rate/min"
    },
    {
     "expr": "openweather_snow1h{location=\"Odawara, JP\", job=\"open-weather\"}",
     "legendFormat": "Snowfall rate/min"
    }
   ]
  },
  { "title": "室内環境", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remo_temperature{name=\"リビング\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remo_humidity{name=\"リビング\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Illumination",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remo_illumination{name=\"リビング\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "remo_temperature{name=\"リビング\"}",
     "legendFormat": "remo_temperature"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "remo_humidity{name=\"リビング\"}",
     "legendFormat": "remo_humidity"
    }
   ]
  },
  {
   "title": "Illumination",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 49 },
   "targets": [
    {
     "expr": "remo_illumination{name=\"リビング\"}",
     "legendFormat": "illumination"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    { "expr": "remo_temperature", "legendFormat": "Temperature" },
    { "expr": "remo_humidity", "legendFormat": "Humidity" },
    { "expr": "remo_illumination", "legendFormat": "Illumination" }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"D35177F149DD\"}",
     "legendFormat": "リビング両開き1"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"F24D14A6A42D\"}",
     "legendFormat": "リビング両開き2"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"FE9806BECC84\"}",
     "legendFormat": "リビングPC前"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"F1A71B2E9D9A\"}",
     "legendFormat": "寝室"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"D35177F149DD\"}",
     "legendFormat": "リビング両開き1"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"F24D14A6A42D\"}",
     "legendFormat": "リビング両開き2"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"FE9806BECC84\"}",
     "legendFormat": "リビングPC前"
    },
    {
     "expr": "switchbot_curtain_battery{job=\"switchbot\", DeviceID=\"F1A71B2E9D9A\"}",
     "legendFormat": "寝室"
    }
   ]
  },
  { "title": "電力", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "remo_measured_instantaneous_energy_watt",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 7, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "remo_measured_instantaneous_energy_watt{name=\"Remo E Lite\"}",
     "legendFormat": "Power Consumption"
    }
   ]
  }
 ]
}