global:
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'remo-exporter'
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
        - remo-exporter:9352
  - job_name: 'contabo-minecraft'
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
        - x.x.x.x:9100
  - job_name: 'minecraft-stats'
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
        - x.x.x.x:9940
  - job_name: 'open-weather'
    metrics_path: /metrics
    scrape_interval: 180s
    static_configs:
      - targets:
        - x.x.x.x:9494
  - job_name: 'switchbot'
    metrics_path: /metrics
    scrape_interval: 180s
    static_configs:
      - targets:
        - x.x.x.x:9495
    
